spring.application.name=apigenarator

# Configuraci?n de la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/apigenerator
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=MiClaveUltraSeguraDe32CaracteresOMas123456
jwt.expiration=3600000

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# Liquibase Configuration
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.default-schema=public

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tu_correo@gmail.com
spring.mail.password=tu_password_o_app_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.ui-base-url=http://localhost:4200
app.activate-account-url=/activate-account
app.reset-password-url=/reset-password
